In [1]:
#import the packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#to read the file
file_path=""
pd.read_csv(file_path,sep=";")

FileNotFoundError: [Errno 2] No such file or directory: ''

In [5]:
#create the file
list1=["ram","raheem","robert"]
list2=[30,31,32]
cols=["name","age"]
names=pd.DataFrame(zip(list1,list2),columns=cols)

In [7]:
names

     name  age
0     ram   30
1  raheem   31
2  robert   32

In [9]:
names

     name  age
0     ram   30
1  raheem   31
2  robert   32

In [11]:
#save the file
names.to_csv("D:\\course videos\\naresh it ds\\python-sessions-2\\name.csv")

In [13]:
#it will not create extra column as index
names.to_csv("names1.csv")

In [15]:
names.to_csv("names1.csv",index=False)

In [17]:
#to read the file
file_path="C:\\Users\\ankan\\names1.csv"
pd.read_csv(file_path)

     name  age
0     ram   30
1  raheem   31
2  robert   32

In [19]:
file_path="D:\\course videos\\naresh it ds\\python-sessions-2\\names.csv"
pd.read_csv(file_path)

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\course videos\\naresh it ds\\python-sessions-2\\names.csv'

In [21]:
file_path="C:\\Users\\ankan\\names1.csv"
pd.read_csv(file_path)

     name  age
0     ram   30
1  raheem   31
2  robert   32

In [23]:
names
#waht is the nm of dataframe:names
#what is the name of the column you what add:city
#how many rows we have in original data:3
#what is u r new data ["hyd","chenni","bng"]

     name  age
0     ram   30
1  raheem   31
2  robert   32

In [25]:
names['city']=["hyd","chenni","bng"]

In [27]:
names

     name  age    city
0     ram   30     hyd
1  raheem   31  chenni
2  robert   32     bng

In [29]:
names[]id=[1,2,3,4]

SyntaxError: invalid syntax (2359196467.py, line 1)

In [31]:
names.drop("city",
           axis=1,
           inplace=True)

In [33]:
names

     name  age
0     ram   30
1  raheem   31
2  robert   32

In [41]:
dict1={"names":["ram","raheem","robert"],"age":[30,31,32]}
dict1

{'names': ['ram', 'raheem', 'robert'], 'age': [30, 31, 32]}

In [43]:
pd.DataFrame(dict1)
#the keys actomatically becomes the columns

    names  age
0     ram   30
1  raheem   31
2  robert   32

In [47]:
pd.DataFrame(dict1,columns=["A","B"])

Empty DataFrame
Columns: [A, B]
Index: []

In [49]:
pd.DataFrame(dict1,index=["A","B","C"])

    names  age
A     ram   30
B  raheem   31
C  robert   32