In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
dict1={'names':['ram','sita','laxman',np.nan],
     'age':[30,31,np.nan,33],
     'city':[np.nan,'hyd','pune','chennai']}
df=pd.DataFrame(dict1)

In [17]:
df.isnull()

   names    age   city
0  False  False   True
1  False  False  False
2  False   True  False
3   True  False  False

In [19]:
df.isnull().sum()

names    1
age      1
city     1
dtype: int64

In [29]:
df.isnull().sum().count()

3

In [21]:
df.isna()

   names    age   city
0  False  False   True
1  False  False  False
2  False   True  False
3   True  False  False

In [31]:
df.fillna(40,inplace=True)

In [37]:
df.dtypes

names     object
age      float64
city      object
dtype: object

method_2

In [53]:
dict1={'names':['ram','sita','laxman',np.nan],
     'age':[30,31,np.nan,33],
     'city':[np.nan,'hyd','pune','chennai']}
df=pd.DataFrame(dict1)

df['names'].fillna("Raheem",inplace=True)
df['age'].fillna(32,inplace=True)
df['city'].fillna("blr",inplace=True)
df

C:\Users\ankan\AppData\Local\Temp\ipykernel_29160\2040574695.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['names'].fillna("Raheem",inplace=True)
C:\Users\ankan\AppData\Local\Temp\ipykernel_29160\2040574695.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(32,inplace=True)
C:\Users\ankan\AppData\Local\Temp\ipykernel_29160\2040574695.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['city'].fillna("blr",inplace=True)

    names   age     city
0     ram  30.0      blr
1    sita  31.0      hyd
2  laxman  32.0     pune
3  Raheem  33.0  chennai

method-3
*pad
*bfill
*backfill
*ffill

In [49]:
 df.fillna(method='pad')

C:\Users\ankan\AppData\Local\Temp\ipykernel_29160\1822911545.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='pad')

    names   age     city
0     ram  30.0       40
1    sita  31.0      hyd
2  laxman  40.0     pune
3      40  33.0  chennai

In [55]:
dict1={'names':['ram','sita','laxman',np.nan],
     'age':[30,31,np.nan,33],
     'city':[np.nan,'hyd','pune','chennai']}
df=pd.DataFrame(dict1)

In [67]:
print("-----or-------")
print(df)
print('-----pad-----')
print(df.fillna(method='pad'))
print('-----ffill-----')
print(df.fillna(method='ffill'))
print('-----bfill-----')
print(df.fillna(method='bfill'))
print('-----backfill-----')
print(df.fillna(method='backfill'))

-----or-------
    names   age     city
0     ram  30.0      NaN
1    sita  31.0      hyd
2  laxman   NaN     pune
3     NaN  33.0  chennai
-----pad-----
    names   age     city
0     ram  30.0      NaN
1    sita  31.0      hyd
2  laxman  31.0     pune
3  laxman  33.0  chennai
-----ffill-----
    names   age     city
0     ram  30.0      NaN
1    sita  31.0      hyd
2  laxman  31.0     pune
3  laxman  33.0  chennai
-----bfill-----
    names   age     city
0     ram  30.0      hyd
1    sita  31.0      hyd
2  laxman  33.0     pune
3     NaN  33.0  chennai
-----backfill-----
    names   age     city
0     ram  30.0      hyd
1    sita  31.0      hyd
2  laxman  33.0     pune
3     NaN  33.0  chennai

C:\Users\ankan\AppData\Local\Temp\ipykernel_29160\4224038666.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df.fillna(method='pad'))
C:\Users\ankan\AppData\Local\Temp\ipykernel_29160\4224038666.py:6: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df.fillna(method='ffill'))
C:\Users\ankan\AppData\Local\Temp\ipykernel_29160\4224038666.py:8: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df.fillna(method='bfill'))
C:\Users\ankan\AppData\Local\Temp\ipykernel_29160\4224038666.py:10: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df.fillna(method='backfill'))

In [63]:
print("-----or-------")
print(df)
print('-----pad-----')
print(df.fillna(method='pad',axis=1))
print('-----ffill-----')
print(df.fillna(method='ffill',axis=1))
print('-----bfill-----')
print(df.fillna(method='bfill',axis=1))
print('-----backfill-----')
print(df.fillna(method='backfill',axis=1))

-----or-------
    names   age     city
0     ram  30.0      NaN
1    sita  31.0      hyd
2  laxman   NaN     pune
3     NaN  33.0  chennai
-----pad-----
    names     age     city
0     ram    30.0     30.0
1    sita    31.0      hyd
2  laxman  laxman     pune
3     NaN    33.0  chennai
-----ffill-----
    names     age     city
0     ram    30.0     30.0
1    sita    31.0      hyd
2  laxman  laxman     pune
3     NaN    33.0  chennai
-----bfill-----
    names   age     city
0     ram  30.0      NaN
1    sita  31.0      hyd
2  laxman  pune     pune
3    33.0  33.0  chennai
-----backfill-----
    names   age     city
0     ram  30.0      NaN
1    sita  31.0      hyd
2  laxman  pune     pune
3    33.0  33.0  chennai

C:\Users\ankan\AppData\Local\Temp\ipykernel_29160\4173341199.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df.fillna(method='pad',axis=1))
C:\Users\ankan\AppData\Local\Temp\ipykernel_29160\4173341199.py:6: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df.fillna(method='ffill',axis=1))
C:\Users\ankan\AppData\Local\Temp\ipykernel_29160\4173341199.py:8: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df.fillna(method='bfill',axis=1))
C:\Users\ankan\AppData\Local\Temp\ipykernel_29160\4173341199.py:10: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(df.fillna(method='backfill',axis=1))

knn

In [69]:
 dict1={'names':['ram','sita','laxman',np.nan],
     'age':[30,31,np.nan,33],
     'city':[np.nan,'hyd','pune','chennai']}
df=pd.DataFrame(dict1)
df

    names   age     city
0     ram  30.0      NaN
1    sita  31.0      hyd
2  laxman   NaN     pune
3     NaN  33.0  chennai

In [71]:
mean_age=df['age'].mean()
df['age'].fillna(mean_age)

0    30.000000
1    31.000000
2    31.333333
3    33.000000
Name: age, dtype: float64

In [73]:
median_age=df['age'].median()
df['age'].fillna(median_age)

0    30.0
1    31.0
2    31.0
3    33.0
Name: age, dtype: float64